"""Add relationships

Revision ID: 00b068aaad90
Revises: 658c9d72148a
Create Date: 2026-06-29 08:58:03.667042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b068aaad90'
down_revision: Union[str, Sequence[str], None] = '658c9d72148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user1_id', sa.Uuid(), nullable=False))
    op.add_column('conversations', sa.Column('user2_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('conversations_used2_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_used1_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user2_id'], ['id'])
    op.drop_column('conversations', 'used1_id')
    op.drop_column('conversations', 'used2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('used2_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('used1_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_used1_id_fkey'), 'conversations', 'users', ['used1_id'], ['id'])
    op.create_foreign_key(op.f('conversations_used2_id_fkey'), 'conversations', 'users', ['used2_id'], ['id'])
    op.drop_column('conversations', 'user2_id')
    op.drop_column('conversations', 'user1_id')
    # ### end Alembic commands ###
